### ISSUE TITLE
Quickstart Guide?

### ISSUE THREAD

**Issue by windowshopr** [DrSquidX/Ethical-Hacking-Scripts#1]
First of all, you're a genius. I'm interested in getting into this field, and I stumbled upon your repo. Hallelujah!

First off, I'm looking at getting your SquidNet2 script running, and am running into an issue, hoping you can shed some light on it for me.

I'm running Windows 10, Python 3.7, and using XAMPP to run a local Apache server:

![image](https://user-images.githubusercontent.com/40477419/140252665-32f1214c-7c38-4faa-a9dd-acaa738f78a5.png)

I fire up squidnet2admin.py, it asks me for the server details. I enter in 127.0.0.1 and have tried both port 80 and 443. After entering the port number and hitting enter, it sits there for several minutes, then tells me the connection is successful, asks me for the admin user name and password, which by default according the PHPAdmin of XAMPP is root and no password. I enter that, and it instantly tells me:

```
[+] Enter the Admin Account name: root
[+] Enter the Admin Account password:
[+] Your connection to the server has been terminated. Please try and reconnecting to the server you were just on.
[+] Are you connecting to a new server or one you've connected to?(new/old):
```

Wondering if I'm doing something in the wrong order or looking for a little guidance. Thanks a lot! Keep up the great work!

**Comment by DrSquidX** [comment]
Hello There,

The error of the script does not lie in the way you are running it, it's simply the credentials being inputted. The reason this is the case, is because the server is kicking any clients who enter incorrect credentials. I apologize not having specification for the script, as schoolwork has gotten in the way of free time. In the SquidNet2 script, there is a configuration file that is automatically generated in the Server's current working directory(should be called 'server.config'), where all of the credentials should be located there. These are the default settings for the server:
```
hostip = localhost
hostport = 8080
external_host = localhost
external_port = 8080
logfile = log.txt
admin_name = admin
admin_password = adminpassword12345
enc_key = iC0g4NM4xy5JrIbRV-8cZSVgFfQioUX8eTVGYRhWlF8=
ftp_dir = Bot_Files
ransomware_active = f
```
The credentials lie simply where it says 'admin_name' and 'admin_password', and you can change those values if needed(You probably should because 'adminpassword12345' is not a suitable password). Those are the credentials needed for admin script to log into the server. I also realized that the version of SquidNet2 in this repository is also outdated, as I have a separate repository it here(In case you didn't already know): https://github.com/DrSquidX/SquidNet2
Also make sure that you have the most up-to-date version of the scripts, as functionality and feature updates come occasionally(I might add self-updating like on my DatCord Script). Hopefully I was able to properly answer your queries, and also solve some of the issues.

Thanks for the support! - DrSquid

**Comment by windowshopr** [comment]
Understandable, I'm taking 7 classes in post-secondary right now haha but looking to grow in this field and found your repo and was like :D haha

Thanks for the prompt reply, and I will keep at it on my end, thanks a lot for the direction! Keep it up!

**Comment by windowshopr** [comment]
Got it runnin! Can't wait to play with this.

For any others, run SquidNet2.py in a command window, follow the instructions as needed. Then with that running, open another command window and run SquidNet2Admin.py using the login/server information from the newly created server.config file (open in notepad to get the port number, admin username and admin password, on Windows the port will be 127.0.0.1). Then you'll see a new SquidBot.py file. This is the file that you'll want to run on the target machine. You're off the races then! Thanks again!

**Comment by DrSquidX** [comment]
No problem! I'm glad that you got it working! Thanks for the further instruction for other users as well, and I plan to add more instruction in my newer repository. - DrSquid
